version: '3.8'
services:
    auth-service:
        container_name: default-auth-service
        image: test/default-auth-service-test:0.0.1-SNAPSHOT
#        networks:
#            - csc7-net
#        depends_on:
#            - config-server
#            - redis
        expose:
            - "8080"
        ports:
            - "8080:8080"

#networks:
#    csc7-net:
#        driver: bridge 
#        ipam:
#            config:
#                - subnet: 172.16.57.0/24

